services:
  media-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-media-service:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiric_media_service
    env_file:
      - ./.env
    environment:
      # .env dosyasındaki değişkenleri, Rust kodunun beklediği isimlere atıyoruz.
      - GRPC_PORT=${INTERNAL_GRPC_PORT_MEDIA}
      - RTP_PORT_MIN=${EXTERNAL_RTP_PORT_MIN}
      - RTP_PORT_MAX=${EXTERNAL_RTP_PORT_MAX}
      - RTP_HOST=0.0.0.0
    ports:
      # Dış RTP port aralığını, içerideki aynı aralığa yönlendiriyoruz.
      - "${EXTERNAL_RTP_PORT_MIN}-${EXTERNAL_RTP_PORT_MAX}:${EXTERNAL_RTP_PORT_MIN}-${EXTERNAL_RTP_PORT_MAX}/udp"
    networks:
      - sentiric-net
    restart: always

networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    external: true