# docker-compose.service.yml
# Geliştirme ortamı

networks:
  sentiric-net: { name: "${NETWORK_NAME:-sentiric-net}", driver: bridge }


services:
  # --- TELEKOM & MEDYA KATMANI ---
  media-service:
    build: { context: ../sentiric-media-service }
    env_file: ["${ENV_FILE_PATH}"]
    volumes:
      - ../sentiric-media-record:/sentiric-media-record:rw"
      - "${CONFIG_REPO_PATH}/tls/certs:/etc/sentiric/tls:ro"
    ports: 
      - "${MEDIA_SERVICE_PORT}:${MEDIA_SERVICE_PORT}"
      - "${MEDIA_SERVICE_METRICS_PORT}:${MEDIA_SERVICE_METRICS_PORT}"      
      - "${MEDIA_SERVICE_GRPC_PORT}:${MEDIA_SERVICE_GRPC_PORT}"
      - "${RTP_SERVICE_PORT_MIN}-${RTP_SERVICE_PORT_MAX}:${RTP_SERVICE_PORT_MIN}-${RTP_SERVICE_PORT_MAX}/udp"
    networks: [sentiric-net]
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50052"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s