# docker-compose.service.yml (NİHAİ)

services:
  media-service:

    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env
    
    environment:
      # Asset'lerin Docker içindeki ana klasörünü belirtiyoruz.
      - ASSETS_BASE_PATH=/app/assets

    tty: true

    ports:
      - "${EXTERNAL_RTP_PORT_MIN:-10000}-${EXTERNAL_RTP_PORT_MAX:-10600}:${EXTERNAL_RTP_PORT_MIN:-10000}-${EXTERNAL_RTP_PORT_MAX:-10600}/udp"
      - "50052:50052"

    mem_limit: 256m
    cpus: 0.5

    restart: always
    init: true