services:
  media-service:
    container_name: sentiric_media_service

    build:
      context: .
      dockerfile: Dockerfile
      # Artık DOCKER_TARGET yok.

    # image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-media-service:${TAG:-latest}

    env_file:
      - .env
    
    # tty: true kalsın, iyi bir alışkanlıktır.
    tty: true

    ports:
      - "${EXTERNAL_RTP_PORT_MIN:-10000}-${EXTERNAL_RTP_PORT_MAX:-10010}:${EXTERNAL_RTP_PORT_MIN:-10000}-${EXTERNAL_RTP_PORT_MAX:-10010}/udp"
      - "50052:50052"

    mem_limit: 256m
    cpus: 0.5

    restart: always
    init: true