services:
  media-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-media-service:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiric_media_service
    # Bu servis için özel .env dosyasını yükler
    env_file:
      - ./.env
    # Ana .env dosyasından PUBLIC_IP'yi alır (opsiyonel ama iyi pratik)
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
    ports:
      # Dış RTP port aralığını, içerideki aynı aralığa yönlendiriyoruz.
      - "${EXTERNAL_RTP_PORT_MIN}-${EXTERNAL_RTP_PORT_MAX}:${EXTERNAL_RTP_PORT_MIN}-${EXTERNAL_RTP_PORT_MAX}/udp"
      # gRPC portunu test için dışarı açmak gerekebilir
      - "50052:50052"
    restart: always