services:
  media-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-media-service:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiric_media_service
    env_file:
      - ./.env
    environment:
      # Rust kodumuz bu değişkenleri bekliyor, .env'den direkt alıyoruz.
      - GRPC_PORT=${GRPC_PORT_MEDIA}
      - RTP_PORT_MIN=${RTP_PORT_MIN}
      - RTP_PORT_MAX=${RTP_PORT_MAX}
      # Rust kodumuz RTP_HOST bekliyor, şimdilik sabit bir değer verelim.
      - RTP_HOST=0.0.0.0      
    ports:
      # gRPC portunu haritalamaya gerek yok, dahili ağdan erişilir.
      # Sadece RTP portlarını haritalıyoruz ki dış dünyadan ses gelebilsin.
      - "${RTP_PORT_MIN:-10000}-${RTP_PORT_MAX:-20000}:${RTP_PORT_MIN:-10000}-${RTP_PORT_MAX:-20000}/udp"
    networks:
      - sentiric-net
    restart: always

networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge