
services:
  media-service:
    container_name: sentiric_media_service

    # build ve image aynı anda kullanılabilir ama dikkatle
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET:-development}

    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-media-service:${TAG:-latest}

    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,sentiric_media_service=debug
      - INTERNAL_GRPC_PORT_MEDIA=50052
      - EXTERNAL_RTP_PORT_MIN=10000
      - EXTERNAL_RTP_PORT_MAX=10010
      - RTP_HOST=0.0.0.0

    ports:
      - "${EXTERNAL_RTP_PORT_MIN:-10000}-${EXTERNAL_RTP_PORT_MAX:-10010}:${EXTERNAL_RTP_PORT_MIN:-10000}-${EXTERNAL_RTP_PORT_MAX:-10010}/udp"
      - "50052:50052"

    mem_limit: 256m
    cpus: 0.5

    restart: always
    init: true
